name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['main', 'node-js']
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
        # Step 1: Checkout the repository
        - name: Checkout
            uses: actions/checkout@v4

        # Step 2: Create the settings.json file
        - name: Create settings.json
            run: |
            echo '{
                "texturepack": "default",
                "graphics": {
                    "foliage": true,
                    "fxaa": true
                },
                "generation": {
                    "world_size": 8
                }
            }' > ./settings.json

        # Step 3: Setup GitHub Pages
        - name: Setup Pages
            uses: actions/configure-pages@v4

        # Step 4: Upload the static content
        - name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
            # Specify the directory containing the static files
            path: './'

        # Step 5: Deploy to GitHub Pages
        - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
